rawx(Go): Improve error message when the XATTRs of the volume are wrong
open-io/oio-sds pull request #2092
Opened 2020-11-09 16:09 UTC by AymericDu

##### SUMMARY

Improve error message when the XATTRs of the volume are wrong

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

- rawx (Go)

##### SDS VERSION

```
openio 5.6.2.dev2
```

2020-11-09 17:06 UTC, fatpat requested changes

2020-11-09 17:06 UTC, fatpat commented on rawx/filerepo.go
> +	return fmt.Errorf("XATTR '%s' of the '%s' mismatch with '%s'",
- `mismatches`
- and having something like `XATTR 'user.server.type` of the `/mnt/nvme0n1/OPENIO/rawx-0` mismatches with 'rawx'` is not very "english" I would say

Maybe `XATTR '%s' of '%s' mismatches with '%s'` or `XATTR('%s', '%s') mismatches with '%s'`

2020-11-09 17:15 UTC, fatpat approved these changes

2020-11-09 20:55 UTC, cdelgehier approved these changes

2020-11-10 09:17 UTC, murlock approved these changes

2020-11-10 09:17 UTC, merged