Various fixes and enhancements
open-io/oio-sds pull request #2102
Opened 2020-12-15 09:38 UTC by murlock

##### SUMMARY

This PR will bring:
- some few fixes for CLI
- stats when a sync occurs
- expose sqlite stats through an admin request on `container/get_properties`

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
sqliterepo, CLI

##### SDS VERSION
```
5.x
```

##### ADDITIONAL INFORMATION
```
$ openio container show big
+----------------------+-----------------------------------------------------------------------------+
| Field                | Value                                                                       |
+----------------------+-----------------------------------------------------------------------------+
| account              | AUTH_88fddfcf6d6c4a85baa1fc27c0ee24bf                                       |
| base_name            | 30AE0C4B4F4E75E44CBC92465BACCCD87A98CEB39F0C967230D20272019CCB4E.1          |
| bucket               | big                                                                         |
| bytes_usage          | 57.412GB                                                                    |
| container            | backup-msdb+segments%2FMSDB-IN-14-AG1%2FMSDB-IN-14-AG1%2FKeolisGroup_Import |
| ctime                | 1594304161                                                                  |
| damaged_objects      | 0                                                                           |
| max_versions         | Namespace default                                                           |
| missing_chunks       | 0                                                                           |
| objects              | 6.848K                                                                      |
| quota                | Namespace default                                                           |
| stats.freelist_count | 3196841                                                                     |
| stats.page_count     | 3206562                                                                     |
| stats.page_size      | 4096                                                                        |
| stats.space_wasted   | 99.70% (est. 13.094G)                                                       |
| status               | Enabled                                                                     |
| storage_policy       | Namespace default                                                           |
+----------------------+-----------------------------------------------------------------------------+
```

2020-12-16 11:13 UTC, fvennetier requested changes

2020-12-16 11:13 UTC, fvennetier commented on sqliterepo/sqlite_utils.c
> +	asprintf(&tmp, "%ld", _sqlx_get_number(sq3, "PRAGMA main.page_count"));
Danger ! Danger ! Danger !
`asprintf` is a GNU C library function, whereas `g_ptr_array_add` (and all other functions we use) are GLib functions. GLib has its own memory management system.
Use `g_strdup_printf("%"G_GINT64_FORMAT, ...)` instead.

2020-12-16 11:13 UTC, fvennetier commented on sqliterepo/sqlite_utils.c
> +	int result = -1;
`int64_t` and `int` should be both replaced by `gint64`.

2020-12-18 14:25 UTC, fvennetier approved these changes

2020-12-22 08:17 UTC, AymericDu approved these changes

2020-12-22 09:07 UTC, merged